import HomeContent from "@/components/HomeContent";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Voice Tool || DLC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
      <main className="bg-home h-screen bg-no-repeat bg-cover bg-center">
        <Navbar />
        <HomeContent />
      </main>
    </>
  );
}
